name: Smoke Test CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Execute base install
        run: chmod +x ./setup.sh
      - name: Execute ZSH install
        run: chmod +x ./install-zsh.sh
